### ISSUE TITLE
Add "post_run" actions

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/rigit#19]
We can perhaps add these optional settings to the config file:

```yaml
before:
- arbitrary command -to run
- another --command -to run
- command with %{param}

after:
- arbitrary command -to run
- another --command -to run
```
