### ISSUE TITLE
Add config to prevent "directory not empty" warning

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/rigit#32]
Some rigs can be additive in nature, so having this warning is just annoying.

Perhaps, the config YAML should allow:

```yaml
options:
    verify_empty_directory: false

intro: ...

params: ...
```
