### ISSUE TITLE
Add condition to input params

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/rigit#35]
Perhaps we can add `condition` to the `params` section in the config, like so:

```yaml
params:
  bin:
    prompt: "Include executable?"
    type: yesno
    default: yes

  binname:
    prompt: "Name of the executable:"
    type: text
    default: mybin
    condition: bin=yes
```
